### PR TITLE
Suggested code cleanup & fix

### PR DESCRIPTION
**Pull request by ewels**
Hi @Pacomito!

Great that you're getting so far with your custom module! Here's a quick pull-request with a bit of cleaning. Mostly, I just removed all of the Python build files cruft that is created when you install a package. You don't need any of it to be tracked with source control, so I deleted it and blocked it from being added back in the future by adding a `.gitignore` file.

Secondly, I moved the files back a directory so that `setup.py` is in the root. No strong reason for this, it's just more typical best practice in my experience.

Thirdly, I removed some unused import statements that were making it tricky for me to install the plugin.

Finally, I fixed the config problem discussed on gitter, with `config.kwargs.get('disable_plugin')` always returning `True` and preventing the `scChIPseq_plugin_execution_start` function from doing anything helpful.

I hope this is helpful! Shout if you have any questions and feel free to merge or ignore as you see fit.

Cheers,

Phil

### CODE REVIEW

**Comment by Pacomito** [comment]
Hi Phil, Thanks very much  :100: ! I must have let a lot of unused import statements, good that you removed it !
 

> Finally, I fixed the config problem discussed on gitter, with config.kwargs.get('disable_plugin') always returning True and preventing the scChIPseq_plugin_execution_start function from doing anything helpful. 
What was the reason that this was always  return true ? I can't find where it was discussed on gitter 
I will retry and hopefully it will work .
Thanks again :+1:

**Comment by ewels** [comment]
`pip install importchecker` is your friend 😉 

Gitter messages:

> ok, it's because of this line: https://github.com/Pacomito/MultiQC_scChIP_seq/blob/d1de7b96652fc902b6c4aa1195fadf604517fd43/scChIPseq/scChIPseq/custom_code.py#L29
The second argument of the `.get()` call in Python is the default value, if it's not set
You have no other mentions of the disable_plugin config attribute anywhere (you removed the cli code), so it's not set. In this line you're setting it to True if it's not set. So that line always returns true, meaning that the function returns before doing anything
simple fix is just to remove the `True` - then the default value of None will be returned if it's not set, which evaluates to False and the rest of the code fires.
Was nothing wrong with your setup hooks or installation method

Tutorial on `get` with example usage: https://www.tutorialspoint.com/python/dictionary_get.htm

**Comment by Pacomito** [comment]
Oh okay I get it I shouldn't have removed some parts of the original code :/ I did this because I didn't use the 'cli' command line options - but I didn't see that this line was linked with what I deleted !
I kinda guessed the installation was not wrong because multiqc could recognised the scChIPseq module but I was indeed puzzled why it couldn't run the custom_code.py, but now I know ! 
 Thanks again for explaining everything. One day (hopefully) when our pipeline will be accessible for everyone I will try to make make this plugin a bit "less artisanal" and available for all multiqc users .

**Comment by ewels** [comment]
No problem! It was an easy one to miss. I just deleted it in that final commit and it should work fine now 👍 

Sounds great anyway - let me know if you need any pointers in the future!

**Pull request merged**
